// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feedback.proto

package feedback

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCode struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseCode) Reset()         { *m = ResponseCode{} }
func (m *ResponseCode) String() string { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()    {}
func (*ResponseCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{0}
}

func (m *ResponseCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCode.Unmarshal(m, b)
}
func (m *ResponseCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCode.Marshal(b, m, deterministic)
}
func (m *ResponseCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCode.Merge(m, src)
}
func (m *ResponseCode) XXX_Size() int {
	return xxx_messageInfo_ResponseCode.Size(m)
}
func (m *ResponseCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCode proto.InternalMessageInfo

func (m *ResponseCode) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseCode) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type FeedbackMessage struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=BookingCode,proto3" json:"BookingCode,omitempty"`
	PassengerId          int32    `protobuf:"varint,2,opt,name=PassengerId,proto3" json:"PassengerId,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedbackMessage) Reset()         { *m = FeedbackMessage{} }
func (m *FeedbackMessage) String() string { return proto.CompactTextString(m) }
func (*FeedbackMessage) ProtoMessage()    {}
func (*FeedbackMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{1}
}

func (m *FeedbackMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedbackMessage.Unmarshal(m, b)
}
func (m *FeedbackMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedbackMessage.Marshal(b, m, deterministic)
}
func (m *FeedbackMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedbackMessage.Merge(m, src)
}
func (m *FeedbackMessage) XXX_Size() int {
	return xxx_messageInfo_FeedbackMessage.Size(m)
}
func (m *FeedbackMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedbackMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FeedbackMessage proto.InternalMessageInfo

func (m *FeedbackMessage) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *FeedbackMessage) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *FeedbackMessage) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type AddPassengerFeedbackRequest struct {
	FeedbackMsg          *FeedbackMessage `protobuf:"bytes,1,opt,name=FeedbackMsg,proto3" json:"FeedbackMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddPassengerFeedbackRequest) Reset()         { *m = AddPassengerFeedbackRequest{} }
func (m *AddPassengerFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*AddPassengerFeedbackRequest) ProtoMessage()    {}
func (*AddPassengerFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{2}
}

func (m *AddPassengerFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPassengerFeedbackRequest.Unmarshal(m, b)
}
func (m *AddPassengerFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPassengerFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *AddPassengerFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPassengerFeedbackRequest.Merge(m, src)
}
func (m *AddPassengerFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_AddPassengerFeedbackRequest.Size(m)
}
func (m *AddPassengerFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPassengerFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPassengerFeedbackRequest proto.InternalMessageInfo

func (m *AddPassengerFeedbackRequest) GetFeedbackMsg() *FeedbackMessage {
	if m != nil {
		return m.FeedbackMsg
	}
	return nil
}

type AddPassengerFeedbackResponse struct {
	ResCode              *ResponseCode    `protobuf:"bytes,1,opt,name=ResCode,proto3" json:"ResCode,omitempty"`
	FeedbackMsg          *FeedbackMessage `protobuf:"bytes,2,opt,name=FeedbackMsg,proto3" json:"FeedbackMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddPassengerFeedbackResponse) Reset()         { *m = AddPassengerFeedbackResponse{} }
func (m *AddPassengerFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*AddPassengerFeedbackResponse) ProtoMessage()    {}
func (*AddPassengerFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{3}
}

func (m *AddPassengerFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPassengerFeedbackResponse.Unmarshal(m, b)
}
func (m *AddPassengerFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPassengerFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *AddPassengerFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPassengerFeedbackResponse.Merge(m, src)
}
func (m *AddPassengerFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_AddPassengerFeedbackResponse.Size(m)
}
func (m *AddPassengerFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPassengerFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPassengerFeedbackResponse proto.InternalMessageInfo

func (m *AddPassengerFeedbackResponse) GetResCode() *ResponseCode {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *AddPassengerFeedbackResponse) GetFeedbackMsg() *FeedbackMessage {
	if m != nil {
		return m.FeedbackMsg
	}
	return nil
}

type GetByPassengerIdRequest struct {
	PassengerId          int32    `protobuf:"varint,2,opt,name=PassengerId,proto3" json:"PassengerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByPassengerIdRequest) Reset()         { *m = GetByPassengerIdRequest{} }
func (m *GetByPassengerIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByPassengerIdRequest) ProtoMessage()    {}
func (*GetByPassengerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{4}
}

func (m *GetByPassengerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByPassengerIdRequest.Unmarshal(m, b)
}
func (m *GetByPassengerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByPassengerIdRequest.Marshal(b, m, deterministic)
}
func (m *GetByPassengerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByPassengerIdRequest.Merge(m, src)
}
func (m *GetByPassengerIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByPassengerIdRequest.Size(m)
}
func (m *GetByPassengerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByPassengerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByPassengerIdRequest proto.InternalMessageInfo

func (m *GetByPassengerIdRequest) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

type GetByPassengerIdResponse struct {
	ResCode              *ResponseCode      `protobuf:"bytes,1,opt,name=ResCode,proto3" json:"ResCode,omitempty"`
	FeedbackMsgs         []*FeedbackMessage `protobuf:"bytes,2,rep,name=FeedbackMsgs,proto3" json:"FeedbackMsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetByPassengerIdResponse) Reset()         { *m = GetByPassengerIdResponse{} }
func (m *GetByPassengerIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetByPassengerIdResponse) ProtoMessage()    {}
func (*GetByPassengerIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{5}
}

func (m *GetByPassengerIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByPassengerIdResponse.Unmarshal(m, b)
}
func (m *GetByPassengerIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByPassengerIdResponse.Marshal(b, m, deterministic)
}
func (m *GetByPassengerIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByPassengerIdResponse.Merge(m, src)
}
func (m *GetByPassengerIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetByPassengerIdResponse.Size(m)
}
func (m *GetByPassengerIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByPassengerIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByPassengerIdResponse proto.InternalMessageInfo

func (m *GetByPassengerIdResponse) GetResCode() *ResponseCode {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *GetByPassengerIdResponse) GetFeedbackMsgs() []*FeedbackMessage {
	if m != nil {
		return m.FeedbackMsgs
	}
	return nil
}

type GetByBookingCodeRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=BookingCode,proto3" json:"BookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByBookingCodeRequest) Reset()         { *m = GetByBookingCodeRequest{} }
func (m *GetByBookingCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetByBookingCodeRequest) ProtoMessage()    {}
func (*GetByBookingCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{6}
}

func (m *GetByBookingCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByBookingCodeRequest.Unmarshal(m, b)
}
func (m *GetByBookingCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByBookingCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetByBookingCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByBookingCodeRequest.Merge(m, src)
}
func (m *GetByBookingCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetByBookingCodeRequest.Size(m)
}
func (m *GetByBookingCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByBookingCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByBookingCodeRequest proto.InternalMessageInfo

func (m *GetByBookingCodeRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type GetByBookingCodeResponse struct {
	ResCode              *ResponseCode    `protobuf:"bytes,1,opt,name=ResCode,proto3" json:"ResCode,omitempty"`
	FeedbackMsg          *FeedbackMessage `protobuf:"bytes,2,opt,name=FeedbackMsg,proto3" json:"FeedbackMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetByBookingCodeResponse) Reset()         { *m = GetByBookingCodeResponse{} }
func (m *GetByBookingCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetByBookingCodeResponse) ProtoMessage()    {}
func (*GetByBookingCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{7}
}

func (m *GetByBookingCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByBookingCodeResponse.Unmarshal(m, b)
}
func (m *GetByBookingCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByBookingCodeResponse.Marshal(b, m, deterministic)
}
func (m *GetByBookingCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByBookingCodeResponse.Merge(m, src)
}
func (m *GetByBookingCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetByBookingCodeResponse.Size(m)
}
func (m *GetByBookingCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByBookingCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByBookingCodeResponse proto.InternalMessageInfo

func (m *GetByBookingCodeResponse) GetResCode() *ResponseCode {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *GetByBookingCodeResponse) GetFeedbackMsg() *FeedbackMessage {
	if m != nil {
		return m.FeedbackMsg
	}
	return nil
}

type DeleteByPassengerIdRequest struct {
	PassengerId          int32    `protobuf:"varint,1,opt,name=PassengerId,proto3" json:"PassengerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByPassengerIdRequest) Reset()         { *m = DeleteByPassengerIdRequest{} }
func (m *DeleteByPassengerIdRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteByPassengerIdRequest) ProtoMessage()    {}
func (*DeleteByPassengerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{8}
}

func (m *DeleteByPassengerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByPassengerIdRequest.Unmarshal(m, b)
}
func (m *DeleteByPassengerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByPassengerIdRequest.Marshal(b, m, deterministic)
}
func (m *DeleteByPassengerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByPassengerIdRequest.Merge(m, src)
}
func (m *DeleteByPassengerIdRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteByPassengerIdRequest.Size(m)
}
func (m *DeleteByPassengerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByPassengerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByPassengerIdRequest proto.InternalMessageInfo

func (m *DeleteByPassengerIdRequest) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

type DeleteByPassengerIdResponse struct {
	ResCode              *ResponseCode `protobuf:"bytes,1,opt,name=ResCode,proto3" json:"ResCode,omitempty"`
	NumberOfDeleted      int32         `protobuf:"varint,2,opt,name=NumberOfDeleted,proto3" json:"NumberOfDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteByPassengerIdResponse) Reset()         { *m = DeleteByPassengerIdResponse{} }
func (m *DeleteByPassengerIdResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteByPassengerIdResponse) ProtoMessage()    {}
func (*DeleteByPassengerIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{9}
}

func (m *DeleteByPassengerIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByPassengerIdResponse.Unmarshal(m, b)
}
func (m *DeleteByPassengerIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByPassengerIdResponse.Marshal(b, m, deterministic)
}
func (m *DeleteByPassengerIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByPassengerIdResponse.Merge(m, src)
}
func (m *DeleteByPassengerIdResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteByPassengerIdResponse.Size(m)
}
func (m *DeleteByPassengerIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByPassengerIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByPassengerIdResponse proto.InternalMessageInfo

func (m *DeleteByPassengerIdResponse) GetResCode() *ResponseCode {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *DeleteByPassengerIdResponse) GetNumberOfDeleted() int32 {
	if m != nil {
		return m.NumberOfDeleted
	}
	return 0
}

func init() {
	proto.RegisterType((*ResponseCode)(nil), "ResponseCode")
	proto.RegisterType((*FeedbackMessage)(nil), "FeedbackMessage")
	proto.RegisterType((*AddPassengerFeedbackRequest)(nil), "AddPassengerFeedbackRequest")
	proto.RegisterType((*AddPassengerFeedbackResponse)(nil), "AddPassengerFeedbackResponse")
	proto.RegisterType((*GetByPassengerIdRequest)(nil), "GetByPassengerIdRequest")
	proto.RegisterType((*GetByPassengerIdResponse)(nil), "GetByPassengerIdResponse")
	proto.RegisterType((*GetByBookingCodeRequest)(nil), "GetByBookingCodeRequest")
	proto.RegisterType((*GetByBookingCodeResponse)(nil), "GetByBookingCodeResponse")
	proto.RegisterType((*DeleteByPassengerIdRequest)(nil), "DeleteByPassengerIdRequest")
	proto.RegisterType((*DeleteByPassengerIdResponse)(nil), "DeleteByPassengerIdResponse")
}

func init() { proto.RegisterFile("feedback.proto", fileDescriptor_7b189e8c8330c03e) }

var fileDescriptor_7b189e8c8330c03e = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x4d, 0xcb, 0xc7, 0xa7, 0x4c, 0x51, 0xc8, 0x6a, 0x62, 0x2d, 0x98, 0x34, 0xbd, 0xc8, 0x69,
	0x0f, 0x95, 0x9b, 0x89, 0x89, 0x68, 0x24, 0x1e, 0x50, 0x5c, 0x7e, 0x01, 0xd0, 0xa1, 0x21, 0x28,
	0x85, 0x6e, 0xd1, 0x10, 0xff, 0xa1, 0xbf, 0xca, 0x50, 0xd8, 0xba, 0x94, 0xa5, 0xc2, 0xc5, 0x53,
	0xb7, 0xd3, 0x99, 0xb7, 0x6f, 0xde, 0xbc, 0x29, 0x1c, 0x0f, 0x10, 0xbd, 0x5e, 0xb7, 0x3f, 0xa2,
	0x93, 0x30, 0x88, 0x02, 0xa7, 0x0e, 0x45, 0x86, 0x7c, 0x12, 0x8c, 0x39, 0xde, 0x05, 0x1e, 0x12,
	0x02, 0xff, 0x16, 0x4f, 0x53, 0xb3, 0xb5, 0x5a, 0x9e, 0xc5, 0x67, 0x52, 0x86, 0x5c, 0x8b, 0xfb,
	0xa6, 0x6e, 0x6b, 0xb5, 0x02, 0x5b, 0x1c, 0x9d, 0x29, 0x94, 0x1e, 0x56, 0x38, 0x2d, 0xe4, 0xbc,
	0xeb, 0x23, 0xb1, 0xc1, 0x68, 0x04, 0xc1, 0x68, 0x38, 0xf6, 0x93, 0xfa, 0x02, 0x93, 0x43, 0x8b,
	0x8c, 0x76, 0x97, 0x73, 0x1c, 0xfb, 0x18, 0x3e, 0x7a, 0x31, 0x5c, 0x9e, 0xc9, 0x21, 0x62, 0xc1,
	0xa1, 0x80, 0x35, 0x73, 0x31, 0x40, 0xf2, 0xee, 0xbc, 0x40, 0xe5, 0xd6, 0xf3, 0x92, 0x6c, 0x11,
	0x67, 0x38, 0x9d, 0x21, 0x8f, 0x88, 0x0b, 0x46, 0xc2, 0x88, 0xfb, 0xf1, 0xf5, 0x86, 0x5b, 0xa6,
	0x29, 0x96, 0x4c, 0x4e, 0x72, 0x3e, 0xa1, 0xaa, 0x86, 0x5c, 0xea, 0x41, 0x2e, 0xe1, 0x80, 0x21,
	0x4f, 0xda, 0x31, 0xdc, 0x23, 0x2a, 0x6b, 0xc5, 0xc4, 0xd7, 0xf4, 0xe5, 0xfa, 0x2e, 0x97, 0x5f,
	0xc3, 0x59, 0x13, 0xa3, 0xc6, 0x5c, 0xea, 0x5f, 0xf4, 0xf2, 0xab, 0x50, 0xce, 0x1c, 0xcc, 0xcd,
	0xe2, 0x7d, 0x59, 0xd7, 0xa1, 0x28, 0x11, 0xe2, 0xa6, 0x6e, 0xe7, 0x94, 0xb4, 0xd7, 0xb2, 0x12,
	0xde, 0xd2, 0x64, 0x25, 0xde, 0xd9, 0x16, 0x70, 0x3e, 0x56, 0xbc, 0xd7, 0x8a, 0xff, 0x42, 0xed,
	0x1b, 0xb0, 0xee, 0xf1, 0x15, 0x23, 0xdc, 0x45, 0x70, 0x6d, 0x53, 0xf0, 0x09, 0x54, 0x94, 0xf5,
	0xfb, 0x72, 0xaf, 0x41, 0xe9, 0x69, 0xf6, 0xd6, 0xc3, 0xf0, 0x79, 0xb0, 0xc4, 0x13, 0xe3, 0x4d,
	0x87, 0xdd, 0x2f, 0xfd, 0x67, 0xc7, 0x3a, 0x18, 0xbe, 0x0f, 0xfb, 0x48, 0x3a, 0x70, 0xaa, 0x32,
	0x2c, 0xa9, 0xd2, 0x8c, 0xd5, 0xb0, 0x2e, 0x68, 0xa6, 0xcb, 0x9b, 0x50, 0x4e, 0x7b, 0x89, 0x98,
	0x74, 0x8b, 0x37, 0xad, 0x73, 0xba, 0xd5, 0x78, 0x02, 0x48, 0xde, 0xf9, 0x15, 0xd0, 0xa6, 0x59,
	0x04, 0x90, 0xca, 0x09, 0x6d, 0x38, 0x51, 0x88, 0x4d, 0x2a, 0x74, 0xfb, 0x08, 0xad, 0x2a, 0xcd,
	0x98, 0x4f, 0xef, 0x7f, 0xfc, 0xb3, 0xbb, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x3c, 0x9b,
	0x3a, 0xfe, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedbackServiceClient is the client API for FeedbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedbackServiceClient interface {
	AddPassengerFeedback(ctx context.Context, in *AddPassengerFeedbackRequest, opts ...grpc.CallOption) (*AddPassengerFeedbackResponse, error)
	GetByPassengerId(ctx context.Context, in *GetByPassengerIdRequest, opts ...grpc.CallOption) (*GetByPassengerIdResponse, error)
	GetByBookingCode(ctx context.Context, in *GetByBookingCodeRequest, opts ...grpc.CallOption) (*GetByBookingCodeResponse, error)
	DeleteByPassengerId(ctx context.Context, in *DeleteByPassengerIdRequest, opts ...grpc.CallOption) (*DeleteByPassengerIdResponse, error)
}

type feedbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedbackServiceClient(cc *grpc.ClientConn) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) AddPassengerFeedback(ctx context.Context, in *AddPassengerFeedbackRequest, opts ...grpc.CallOption) (*AddPassengerFeedbackResponse, error) {
	out := new(AddPassengerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/FeedbackService/AddPassengerFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetByPassengerId(ctx context.Context, in *GetByPassengerIdRequest, opts ...grpc.CallOption) (*GetByPassengerIdResponse, error) {
	out := new(GetByPassengerIdResponse)
	err := c.cc.Invoke(ctx, "/FeedbackService/GetByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetByBookingCode(ctx context.Context, in *GetByBookingCodeRequest, opts ...grpc.CallOption) (*GetByBookingCodeResponse, error) {
	out := new(GetByBookingCodeResponse)
	err := c.cc.Invoke(ctx, "/FeedbackService/GetByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) DeleteByPassengerId(ctx context.Context, in *DeleteByPassengerIdRequest, opts ...grpc.CallOption) (*DeleteByPassengerIdResponse, error) {
	out := new(DeleteByPassengerIdResponse)
	err := c.cc.Invoke(ctx, "/FeedbackService/DeleteByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedbackServiceServer is the server API for FeedbackService service.
type FeedbackServiceServer interface {
	AddPassengerFeedback(context.Context, *AddPassengerFeedbackRequest) (*AddPassengerFeedbackResponse, error)
	GetByPassengerId(context.Context, *GetByPassengerIdRequest) (*GetByPassengerIdResponse, error)
	GetByBookingCode(context.Context, *GetByBookingCodeRequest) (*GetByBookingCodeResponse, error)
	DeleteByPassengerId(context.Context, *DeleteByPassengerIdRequest) (*DeleteByPassengerIdResponse, error)
}

// UnimplementedFeedbackServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFeedbackServiceServer struct {
}

func (*UnimplementedFeedbackServiceServer) AddPassengerFeedback(ctx context.Context, req *AddPassengerFeedbackRequest) (*AddPassengerFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPassengerFeedback not implemented")
}
func (*UnimplementedFeedbackServiceServer) GetByPassengerId(ctx context.Context, req *GetByPassengerIdRequest) (*GetByPassengerIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByPassengerId not implemented")
}
func (*UnimplementedFeedbackServiceServer) GetByBookingCode(ctx context.Context, req *GetByBookingCodeRequest) (*GetByBookingCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByBookingCode not implemented")
}
func (*UnimplementedFeedbackServiceServer) DeleteByPassengerId(ctx context.Context, req *DeleteByPassengerIdRequest) (*DeleteByPassengerIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByPassengerId not implemented")
}

func RegisterFeedbackServiceServer(s *grpc.Server, srv FeedbackServiceServer) {
	s.RegisterService(&_FeedbackService_serviceDesc, srv)
}

func _FeedbackService_AddPassengerFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPassengerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).AddPassengerFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/AddPassengerFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).AddPassengerFeedback(ctx, req.(*AddPassengerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByPassengerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/GetByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetByPassengerId(ctx, req.(*GetByPassengerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByBookingCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/GetByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetByBookingCode(ctx, req.(*GetByBookingCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_DeleteByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByPassengerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).DeleteByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeedbackService/DeleteByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).DeleteByPassengerId(ctx, req.(*DeleteByPassengerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPassengerFeedback",
			Handler:    _FeedbackService_AddPassengerFeedback_Handler,
		},
		{
			MethodName: "GetByPassengerId",
			Handler:    _FeedbackService_GetByPassengerId_Handler,
		},
		{
			MethodName: "GetByBookingCode",
			Handler:    _FeedbackService_GetByBookingCode_Handler,
		},
		{
			MethodName: "DeleteByPassengerId",
			Handler:    _FeedbackService_DeleteByPassengerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedback.proto",
}
